## Load data

In [3]:
import json
import pandas as pd
from src.config import DATA_DIR

origin_data_path = DATA_DIR / "data.json"

with open(origin_data_path, "r") as file:
    origin_data = json.load(file)

## Flatten

In [37]:
rows = []
for item in origin_data:
    flat_item = {
        "chunk_id": item.get("chunk_id"),
        "node_type": item.get("node_type"),
        "text": item.get("text"),
        "text_len_char": len(item.get("text")),
        "text_len_word": len(item.get("text").split()),
        "has_amendment": len(item.get("amendment_notes")) > 0,
        "amendment": len(item.get("amendment_notes")),
        **item.get("metadata")
    }
    rows.append(flat_item)

df = pd.DataFrame(rows)

In [10]:
df.head(1)

,chunk_id,node_type,text,text_len_char,text_len_word,has_amendment,document_id,document_type,document_title,doc_identity,...,chapter_title,section_number,section_title,article_number,article_title,clause_number,clause_title,point,lead_in_text,hierarchy_path
0,law_8680dd55cf741ae869eb0f099f1cab4a_a1,article,Bộ luật Lao động quy định tiêu chuẩn lao động;...,317,69,False,8680dd55cf741ae869eb0f099f1cab4a,Bộ luật,Bộ Luật lao động số 45/2019/QH14,45/2019/QH14,...,NHỮNG QUY ĐỊNH CHUNG,None,NaN,1,Phạm vi điều chỉnh,NaN,None,NaN,NaN,"[Bộ Luật lao động số 45/2019/QH14, Chương I. N..."

## Overall

In [38]:
print("OVERALL--------------------")
print(f"Tổng số chunks: {len(df)}")
print(f"Số chunk_id duy nhất: {df['chunk_id'].nunique()}")
print(f"Số document_id duy nhất: {df['document_id'].nunique()}")

print("\nMISSING VALUES (%)---------")
print((round(df.isnull().sum() / len(df) * 100, 1)).sort_values(ascending=False))

OVERALL--------------------
Tổng số chunks: 21447
Số chunk_id duy nhất: 21319
Số document_id duy nhất: 17

MISSING VALUES (%)---------
source_guid           100.0
clause_title          100.0
major_names            63.2
section_title          61.1
expire_date            61.0
point                  59.4
section_number         59.3
lead_in_text           46.2
part_title             41.3
part_number            35.2
article_title          17.7
clause_number          14.9
chapter_title          13.0
chapter_number          6.9
node_type               0.0
chunk_id                0.0
text_len_char           0.0
text                    0.0
amendment               0.0
text_len_word           0.0
signer_names            0.0
signer_title_names      0.0
organ_names             0.0
effect_status_name      0.0
issue_date              0.0
effect_date             0.0
field_names             0.0
doc_identity            0.0
has_amendment           0.0
document_title          0.0
document_type           0.0
document_id             0.0
vbpl_url                0.0
scraped_date            0.0
article_number          0.0
hierarchy_path          0.0
dtype: float64

In [39]:
df.describe()

       text_len_char  text_len_word  amendment  article_number  clause_number
count   21447.000000   21447.000000    21447.0    21447.000000   18252.000000
mean      181.618874      40.170560        0.0      220.569217       2.365549
std       214.956086      47.145628        0.0      157.865081       1.703794
min         7.000000       1.000000        0.0        1.000000       1.000000
25%        69.000000      15.000000        0.0       97.000000       1.000000
50%       130.000000      29.000000        0.0      193.000000       2.000000
75%       234.000000      52.000000        0.0      305.000000       3.000000
max     15147.000000    3310.000000        0.0      777.000000      26.000000

## Các bộ luật được sử dụng

In [49]:
documents = df['document_title'].sort_values(ascending=False).unique()
for idx, doc in enumerate(documents):
    print(f"[{idx}] {doc}")

[0] Bộ luật Tố tụng hình sự số Không số
[1] Bộ luật Tố tụng hình sự số 19/2003/QH11
[2] Bộ luật Tố tụng hình sự số 101/2015/QH13
[3] Bộ luật Tố tụng dân sự số 92/2015/QH13
[4] Bộ luật Tố tụng dân sự số 24/2004/QH11
[5] Bộ luật Lao động số Không số
[6] Bộ luật Lao động số 10/2012/QH13
[7] Bộ luật Hình sự số Không số
[8] Bộ luật Hình sự số 15/1999/QH10
[9] Bộ luật Hình sự số 100/2015/QH13
[10] Bộ luật Hàng hải số 95/2015/QH13
[11] Bộ luật Hàng hải số 42-LCT/HĐNN8
[12] Bộ luật Hàng hải Việt Nam số 40/2005/QH11
[13] Bộ luật Dân sự số Không số
[14] Bộ luật Dân sự số 91/2015/QH13
[15] Bộ luật Dân sự số 33/2005/QH11
[16] Bộ Luật lao động số 45/2019/QH14

In [51]:
effect_status_names = df['effect_status_name'].sort_values(ascending=False).unique()
for idx, name in enumerate(effect_status_names):
    print(f"- {name}")

- Hết hiệu lực toàn bộ
- Hết hiệu lực một phần
- Còn hiệu lực

In [52]:
idx_max = df["text_len_word"].idxmax()
longest_row = df.loc[idx_max]

In [53]:
longest_row

chunk_id                       law_312895f82baae4caa99be7356b6196d2_a89
node_type                                                       article
text                  Pháp nhân thương mại bị kết án đương nhiên đượ...
text_len_char                                                     15147
text_len_word                                                      3310
has_amendment                                                     False
amendment                                                             0
document_id                            312895f82baae4caa99be7356b6196d2
document_type                                                   Bộ luật
document_title                         Bộ luật Hình sự số 100/2015/QH13
doc_identity                                              100/2015/QH13
major_names                                                        None
field_names                                            [Chưa phân loại]
issue_date                                                   2015-11-27
effect_date                                                  2018-01-01
effect_status_name                                Hết hiệu lực một phần
expire_date                                                         NaN
organ_names                                                  [Quốc hội]
signer_title_names                                  [Chủ tịch Quốc hội]
signer_names                                         [Nguyễn Sinh Hùng]
vbpl_url              https://vbpl.vn/van-ban/chi-tiet/bo-luat-hinh-...
source_guid                                                        None
scraped_date                           2026-07-01T01:49:00.626986+07:00
part_number                                                   thứ nhất.
part_title                                         NHỮNG QUY ĐỊNH CHUNG
chapter_number                                                       XI
chapter_title         NHỮNG QUY ĐỊNH ĐỐI VỚI PHÁP NHÂN THƯƠNG MẠI PH...
section_number                                                     None
section_title                                                       NaN
article_number                                                       89
article_title                                               Xóa án tích
clause_number                                                       NaN
clause_title                                                       None
point                                                               NaN
lead_in_text                                                        NaN
hierarchy_path        [Bộ luật Hình sự số 100/2015/QH13, Phần thứ nh...
Name: 3428, dtype: object